[package]
name = "lox-rc"
version = "0.1.0"
edition = "2021"
default-run = "lvm"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "lvm"
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["Performance", "Window"] }
